name: auto-tag on bump

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [main]

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # ensure full history so tags are available

      - name: fetch tags
        run: git fetch --tags --prune

      - name: compare tags
        id: get-tag
        run:
          | # much inspiration from github.com/imputnet/helium/.github/workflows/release-and-tag.yml
          NEW_VERSION=$(jq -r .version src-tauri/tauri.conf.json)
          echo "current version: $NEW_VERSION"

          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "checking out $LATEST_TAG"
          git checkout "tags/$LATEST_TAG" -b release-$LATEST_TAG
          OLD_VERSION=$(jq -r .version src-tauri/tauri.conf.json)
          echo "old version: $OLD_VERSION"

          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
            echo "version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
            echo "old-version=$OLD_VERSION" >> "$GITHUB_OUTPUT"
          fi

      - name: create/update tag
        id: create-tag
        if: steps.get-tag.outputs.version
        uses: actions/github-script@v8
        with: # from https://stackoverflow.com/a/78010013
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.get-tag.outputs.version }}',
              sha: context.sha
            }).catch(err => {
              if (err.status !== 422) throw err;
              github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/v${{ steps.get-tag.outputs.version }}',
                sha: context.sha
              });
            })

      - name: trigger build
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-on-tag.yml',
              ref: 'refs/tags/v${{ steps.get-tag.outputs.version }}',
              inputs: {
                tagName: 'v${{ steps.get-tag.outputs.version }}',
              },
            })
