name: autorelease on bump

permissions:
  contents: write

on: workflow_dispatch # not ready for release yet
# on:
#   push:
#     branches:
#       - main

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # ensure full history so tags are available

      - name: setup v
        uses: vlang/setup-v@v1.4

      - name: fetch tags
        run: git fetch --tags --prune

      - name: compare tags
        id: tag
        run:
          | # much inspiration from github.com/imputnet/helium/.github/workflows/release-and-tag.yml
          v version.v

          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Checking out $LATEST_TAG"
          git checkout "tags/$LATEST_TAG" -b release-$LATEST_TAG
          OLD_VERSION=./version

          git checkout HEAD
          NEW_VERSION=./version

          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
            echo "version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
            {
              printf '### changes\n```\n'
              git log --oneline "$OLD_VERSION.."
              echo '```'
            } | tee body.md
          fi

      - name: Create Release
        if: steps.tag.outputs.version
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.version }}
          name: ${{ steps.tag.outputs.version }}
          body_path: body.md
