name: auto-tag on bump

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [main]

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # ensure full history so tags are available

      - name: fetch tags
        run: git fetch --tags --prune

      - name: install v
        uses: vlang/setup-v@v1.4

      - name: compare tags
        id: get-tag
        run:
          | # much inspiration from github.com/imputnet/helium/.github/workflows/release-and-tag.yml
          NEW_VERSION=$(v run version.v)
          echo "current version: $NEW_VERSION"

          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "checking out $LATEST_TAG"
          git checkout "tags/$LATEST_TAG" -b release-$LATEST_TAG
          OLD_VERSION=$(v run version.v)
          echo "old version: $OLD_VERSION"

          if [ "$OLD_VERSION" != "$NEW_VERSION" ]; then
            echo "version=$NEW_VERSION" >> "$GITHUB_OUTPUT"
            {
              printf '### changes\n```\n'
              git log --oneline "$OLD_VERSION.."
              echo '```'
            } | tee body.md
          fi

      - name: create tag
        if: steps.get-tag.outputs.version
        id: create-tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ steps.get-tag.outputs.version }}
