name: "publish"

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: "tag to build"
        required: true
        default: "0.0.0"
  workflow_call:
    inputs:
      tagName:
        required: true
        type: string

# This is the example from the readme.
# On each push to the `release` branch it will create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri:
    env:
      TAG_NAME: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.tagName }}
    permissions:
      contents: write
      id-token: write

    outputs:
      artifact-name: chiffrage-bin-${{ matrix.platform }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            arch: aarch64
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            arch: x86_64
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
            arch: x86_64
            args: ""
          - platform: "windows-latest"
            arch: x86_64
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: bun install

      - name: build binaries
        run: bun tauri build ${{ matrix.args }}
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

      - name: zip mac .app bundles
        if: matrix.platform == 'macos-latest' # This must match the platform value defined above.
        run: |
          find src-tauri/target -name "*.app" -type d | while read app; do
            ditto -c -k --sequesterRsrc --keepParent "$app" "$app.zip"
            rm -rf "$app"
          done

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chiffrage-artifacts-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            src-tauri/target/**/*.dmg
            src-tauri/target/**/*.app.zip
            src-tauri/target/**/*.exe
            src-tauri/target/**/*.msi
            src-tauri/target/**/*.rpm
            src-tauri/target/**/*.deb
            src-tauri/target/**/*.AppImage

  release:
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    runs-on: ubuntu-latest
    needs: [publish-tauri]

    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - run: ls -R artifacts/

      - name: sign release artifacts
        uses: sigstore/gh-action-sigstore-python@v3.2.0
        with:
          inputs: |
            artifacts/**/*.dmg
            artifacts/**/*.app.zip
            artifacts/**/*.exe
            artifacts/**/*.msi
            artifacts/**/*.rpm
            artifacts/**/*.deb
            artifacts/**/*.AppImage

      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: |
            artifacts/**/*.dmg
            artifacts/**/*.app.zip
            artifacts/**/*.exe
            artifacts/**/*.msi
            artifacts/**/*.rpm
            artifacts/**/*.deb
            artifacts/**/*.AppImage

      - name: make release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ inputs.tagName }}
        run: |
          gh release create $TAG_NAME \
            $(find artifacts -type f -name '*.dmg') \
            $(find artifacts -type f -name '*.app.zip') \
            $(find artifacts -type f -name '*.exe') \
            $(find artifacts -type f -name '*.msi') \
            $(find artifacts -type f -name '*.rpm') \
            $(find artifacts -type f -name '*.deb') \
            $(find artifacts -type f -name '*.AppImage') \
            --generate-notes
