name: create release

on:
  workflow_dispatch:
    inputs:
      tagName:
        description: "tag to build"
        required: true
        default: "0.0.0"
  workflow_call:
    inputs:
      tagName:
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - run: ls -l -R artifacts/

      - name: sign release artifacts
        uses: sigstore/gh-action-sigstore-python@v3.2.0
        with:
          inputs: |
            artifacts/**/*.dmg
            artifacts/**/*.app.zip
            artifacts/**/*.exe
            artifacts/**/*.msi
            artifacts/**/*.rpm
            artifacts/**/*.deb
            artifacts/**/*.AppImage

      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: |
            artifacts/**/*.dmg
            artifacts/**/*.app.zip
            artifacts/**/*.exe
            artifacts/**/*.msi
            artifacts/**/*.rpm
            artifacts/**/*.deb
            artifacts/**/*.AppImage

      - name: make release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ inputs.tagName }}
        run: |
          if [[ $TAG_NAME =~ -[a-zA-Z] ]]; then
            PRERELEASE_FLAG="--prerelease"
          else
            PRERELEASE_FLAG=""
          fi
          gh release create $TAG_NAME $(find artifacts -path '*/release/bundle/*' -type f) --generate-notes $PRERELEASE_FLAG -d
