name: sign release artifacts

permissions:
  contents: write
  id-token: write

on: release

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - name: sign release artifacts
        uses: sigstore/gh-action-sigstore-python@v3.2.0
        with:
          release-signing-artifacts: true
